title: My Blog
description: A personal blog about AI, Data Science, and Technology.
baseurl: "/blog" # No subpath for GitHub Pages root repository
url: "https://pankajbadatia.github.io"
theme: minima
